/**
 * @fileoverview gRPC-Web generated client stub for text2image
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: text2image.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.text2image.TextToImageClient');
goog.provide('proto.text2image.TextToImagePromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.text2image.GenerateImageRequest');
goog.require('proto.text2image.GenerateImageResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.text2image.TextToImageClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.text2image.TextToImagePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.text2image.GenerateImageRequest,
 *   !proto.text2image.GenerateImageResponse>}
 */
const methodDescriptor_TextToImage_GenerateImage = new grpc.web.MethodDescriptor(
  '/text2image.TextToImage/GenerateImage',
  grpc.web.MethodType.UNARY,
  proto.text2image.GenerateImageRequest,
  proto.text2image.GenerateImageResponse,
  /**
   * @param {!proto.text2image.GenerateImageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.text2image.GenerateImageResponse.deserializeBinary
);


/**
 * @param {!proto.text2image.GenerateImageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.text2image.GenerateImageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.text2image.GenerateImageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.text2image.TextToImageClient.prototype.generateImage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/text2image.TextToImage/GenerateImage',
      request,
      metadata || {},
      methodDescriptor_TextToImage_GenerateImage,
      callback);
};


/**
 * @param {!proto.text2image.GenerateImageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.text2image.GenerateImageResponse>}
 *     Promise that resolves to the response
 */
proto.text2image.TextToImagePromiseClient.prototype.generateImage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/text2image.TextToImage/GenerateImage',
      request,
      metadata || {},
      methodDescriptor_TextToImage_GenerateImage);
};


}); // goog.scope

