# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text2image.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'text2image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10text2image.proto\x12\ntext2image\",\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"!\n\x0cTextResponse\x12\x11\n\timage_url\x18\x01 \x01(\t2W\n\x11Text2ImageService\x12\x42\n\rGenerateImage\x12\x17.text2image.TextRequest\x1a\x18.text2image.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text2image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=32
  _globals['_TEXTREQUEST']._serialized_end=76
  _globals['_TEXTRESPONSE']._serialized_start=78
  _globals['_TEXTRESPONSE']._serialized_end=111
  _globals['_TEXT2IMAGESERVICE']._serialized_start=113
  _globals['_TEXT2IMAGESERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
